name: ml_droplet
channels:
  - apple
  - conda-forge
  - defaults
dependencies:
  - anyio=3.5.0
  - appnope=0.1.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - attrs=21.4.0
  - babel=2.9.1
  - backcall=0.2.0
  - beautifulsoup4=4.11.1
  - blas=1.0
  - bleach=4.1.0
  - brotli=1.0.7
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.4.26
  - certifi=2022.6.15
  - cffi=1.15.0
  - cryptography=37.0.1
  - cycler=0.11.0
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=0.8.3
  - fonttools=4.25.0
  - freetype=2.11.0
  - giflib=5.2.1
  - grpcio=1.42.0
  - h5py=3.6.0
  - hdf5=1.12.1
  - idna=3.3
  - ipykernel=6.9.1
  - ipympl=0.8.7
  - ipython=8.3.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jedi=0.18.1
  - jinja2=3.0.3
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.4.0
  - jupyter_client=7.2.2
  - jupyter_core=4.10.0
  - jupyter_server=1.17.1
  - jupyterlab=3.3.2
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.12.0
  - jupyterlab_widgets=1.0.0
  - kiwisolver=1.4.2
  - krb5=1.19.2
  - lcms2=2.12
  - libcurl=7.82.0
  - libcxx=12.0.0
  - libedit=3.1.20210910
  - libev=4.33
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=11.2.0
  - libnghttp2=1.46.0
  - libopenblas=0.3.20
  - libpng=1.6.37
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libtiff=4.2.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libzlib=1.2.12
  - llvm-openmp=12.0.0
  - lz4-c=1.9.3
  - markupsafe=2.1.1
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - matplotlib-inline=0.1.2
  - mistune=0.8.4
  - munkres=1.1.4
  - nbclassic=0.3.5
  - nbclient=0.5.13
  - nbconvert=6.4.4
  - nbformat=5.3.0
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - notebook=6.4.11
  - numpy=1.22.3
  - numpy-base=1.22.3
  - openssl=1.1.1p
  - packaging=21.3
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.0.1
  - pip=21.2.4
  - prometheus_client=0.13.1
  - prompt-toolkit=3.0.20
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.11.2
  - pyopenssl=22.0.0
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.10.5
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.15.1
  - pytz=2022.1
  - pyzmq=22.3.0
  - readline=8.1.2
  - send2trash=1.8.0
  - setuptools=61.2.0
  - sniffio=1.2.0
  - soupsieve=2.3.1
  - sqlite=3.38.5
  - stack_data=0.2.0
  - tensorflow-deps=2.9.0
  - terminado=0.13.1
  - testpath=0.6.0
  - tk=8.6.12
  - tornado=6.1
  - tqdm=4.64.0
  - traitlets=5.1.1
  - typing_extensions=4.1.1
  - tzdata=2022a
  - urllib3=1.26.9
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.37.1
  - widgetsnbextension=3.5.2
  - xz=5.2.5
  - zeromq=4.3.4
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - absl-py==1.1.0
    - astunparse==1.6.3
    - cachetools==5.2.0
    - charset-normalizer==2.1.0
    - flatbuffers==1.12
    - gast==0.4.0
    - google-auth==2.9.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - keras==2.9.0
    - keras-preprocessing==1.1.2
    - libclang==14.0.1
    - markdown==3.3.7
    - oauthlib==3.2.0
    - opencv-python==4.6.0.66
    - opt-einsum==3.3.0
    - protobuf==3.19.4
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyparsing==3.0.9
    - requests==2.28.1
    - requests-oauthlib==1.3.1
    - rsa==4.8
    - six==1.15.0
    - tensorboard==2.9.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow-estimator==2.9.0
    - tensorflow-macos==2.9.2
    - tensorflow-metal==0.5.0
    - termcolor==1.1.0
    - typing-extensions==4.3.0
    - werkzeug==2.1.2
    - wrapt==1.14.1
